version: '3'

services:
  proxy:
    # fix for OpenTelemetry JS always adding a trailing slash to the OTLP endpoints, which is not supported by Jaeger
    image: nginx:alpine
    ports:
      - '4318:4318'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  jaeger:
    image: jaegertracing/jaeger:2.9.0
    hostname: jaeger
    ports:
      - '16686:16686' # Jaeger UI
      - '4317:4317' # OTLP gRPC receiver
      - '4319:4319' # OTLP HTTP receiver for proxy (4318 served by nginx)
    command:
      [
        '--set=receivers.otlp.protocols.http.endpoint=0.0.0.0:4319',
        '--set=receivers.otlp.protocols.grpc.endpoint=0.0.0.0:4317',
      ]
    environment:
      - LOG_LEVEL=verbose
