packages:
  - packages/*
  - examples/*
  - website

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@evilmartians/lefthook'
  - core-js
  - esbuild
  - nitro-codegen
  - node-pty
  - react-native-nitro-modules
  - unrs-resolver
